/**
 * 本地菜单定义结构
 */
export const LOCAL_ROUTES = [
  {
    name: "Veiw",
    path: "/view",
    hidden: false,
    redirect: "noRedirect",
    component: "Layout",
    alwaysShow: true,
    meta: { title: "地图视图", icon: "View", roles: ["admin"] },
    children: [
      {
        path: "multipleSyncedViews",
        component: "view/multipleSyncedViews/index",
        name: "MultipleSyncedViews",
        hidden: false,
        meta: { title: "二三维视图同步", icon: "tongbu-05", roles: ["admin"] },
      },
      {
        path: "rotatable2DMap",
        component: "view/rotatable2DMap/index",
        name: "Rotatable2DMap",
        hidden: false,
        meta: { title: "可旋转的二维地图", icon: "erweiditu", roles: ["admin"] },
      },
      {
        path: "eagleEye",
        component: "view/eagleEye/index",
        name: "EagleEye",
        hidden: false,
        meta: { title: "鹰眼", icon: "ying_eagle", roles: ["admin"] },
      },
    ],
  },
  // {
  //   name: "3dmodel",
  //   path: "/3dmodel",
  //   hidden: false,
  //   redirect: "noRedirect",
  //   component: "Layout",
  //   alwaysShow: true,
  //   meta: { title: "三维模型", icon: "模型", roles: ["admin"] },
  //   children: [
  //     {
  //       path: "gltfModels",
  //       component: "3dmodel/gltfModels/index",
  //       name: "glTF 模型",
  //       hidden: false,
  //       meta: { title: "glTF模型", icon: "gltf", roles: ["admin"] },
  //     },
  //   ],
  // },
  {
    name: "geometries",
    path: "/geometries",
    hidden: false,
    redirect: "noRedirect",
    component: "Layout",
    alwaysShow: true,
    meta: { title: "几何体绘制", icon: "jiheti", roles: ["admin"] },
    children: [
      {
        path: "geometriesDraw",
        component: "geometries/geometriesDraw/index",
        name: "GeometriesDraw",
        hidden: false,
        meta: { title: "常见几何体绘制", icon: "jiheti", roles: ["admin"] },
      },
      {
        path: "sectorDraw",
        component: "geometries/sectorDraw/index",
        name: "SectorDraw",
        hidden: false,
        meta: { title: "扇形绘制", icon: "a-xigua_watermelon-one2", roles: ["admin"] },
      },
      {
        path: "groundPolylineDraw",
        component: "geometries/groundPolylineDraw/index",
        name: "GroundPolylineDraw",
        hidden: false,
        meta: { title: "绘制贴地线", icon: "icon-tiedixian", roles: ["admin"] },
      },
    ],
  },
  {
    name: "3dtile",
    path: "/3dtile",
    hidden: false,
    redirect: "noRedirect",
    component: "Layout",
    alwaysShow: true,
    meta: { title: "3DTiles", icon: "3Dkeshiyufenxi", roles: ["admin"] },
    children: [
      {
        path: "adjustHeight",
        component: "3dtile/adjustHeight/index",
        name: "AdjustHeight",
        hidden: false,
        meta: { title: "调整模型高度", icon: "zidongtiaozhenggaodu", roles: ["admin"] },
      },
      {
        path: "adjustPositionAndScale",
        component: "3dtile/adjustPositionAndScale/index",
        name: "AdjustPositionAndScale",
        hidden: false,
        meta: { title: "改变模型位置旋转及缩放", icon: "galaxy", roles: ["admin"] },
      },
    ],
  },
  {
    name: "Camera",
    path: "/camera",
    hidden: false,
    redirect: "noRedirect",
    component: "Layout",
    alwaysShow: true,
    meta: { title: "相机", icon: "zhaoxiangji", roles: ["admin"] },
    children: [
      {
        path: "cameraVisualization",
        component: "camera/cameraVisualization/index",
        name: "CameraVisualization",
        hidden: false,
        meta: { title: "相机可视化", icon: "zhaoxiangji", roles: ["admin"] },
      },
      {
        path: "cameraControl",
        component: "camera/cameraControl/index",
        name: "CameraControl",
        hidden: false,
        meta: { title: "相机控制", icon: "galaxy", roles: ["admin"] },
      },
    ],
  },
  {
    name: "Material",
    path: "/material",
    hidden: false,
    redirect: "noRedirect",
    component: "Layout",
    alwaysShow: true,
    meta: { title: "材质", icon: "icon-caizhi1", roles: ["admin"] },
    children: [
      {
        path: "changeColor",
        component: "material/changeColor/index",
        name: "ChangeColor",
        hidden: false,
        meta: { title: "变更颜色", icon: "color", roles: ["admin"] },
      },
      {
        path: "gradientMaterial",
        component: "material/gradientMaterial/index",
        name: "GradientMaterial",
        hidden: false,
        meta: { title: "渐变色材质", icon: "icon-jianbiantiao", roles: ["admin"] },
      },
      {
        path: "videoTexture",
        component: "material/videoTexture/index",
        name: "VideoTexture",
        hidden: false,
        meta: { title: "视频材质", icon: "icon-video", roles: ["admin"] },
      },
    ],
  },
  {
    name: "SpaceAnalysis",
    path: "/spaceAnalysis",
    hidden: false,
    redirect: "noRedirect",
    component: "Layout",
    alwaysShow: true,
    meta: { title: "空间分析", icon: "icon-dilikongjianfenxi", roles: ["admin"] },
    children: [
      {
        path: "overlayAnalysis",
        component: "spaceAnalysis/overlayAnalysis/index",
        name: "OverlayAnalysis",
        hidden: false,
        meta: { title: "叠加分析", icon: "icon-diejiafenxi", roles: ["admin"] },
      },
    ],
  },
  {
    name: "Trajectory",
    path: "/trajectory",
    hidden: false,
    redirect: "noRedirect",
    component: "Layout",
    alwaysShow: true,
    meta: { title: "轨迹", icon: "icon-yundanguiji", roles: ["admin"] },
    children: [
      {
        path: "czmlDroneInspection",
        component: "trajectory/czmlDroneInspection/index",
        name: "CzmlDroneInspection",
        hidden: false,
        meta: { title: "CZML无人机巡检推流", icon: "icon-Czml", roles: ["admin"] },
      },
    ],
  },
];
